name: Build & Deploy to App Store and Testflight
on:
  push:
    branches:
      - homolog
      - prod

jobs:
  build_IOS_App:
    name: Build IOS App
    runs-on: macos-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Java Version
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Get dependencies
        run: npm install
      
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: ios
      
      - name: Set Versions
        run: |
          current_version=$(perl -ne 'print "$1" if /"version":\s*"(.*?)"/' package.json)
          echo "MARKETING_VERSION=$current_version" >> ios/ReactNative/Generate.xcconfig
          echo "CURRENT_PROJECT_VERSION=${{ github.run_number }}" >> ios/ReactNative/Generate.xcconfig

      - name: Pods install
        run: pod install
        working-directory: ios

      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.8.0
        with:
          project-path: ios/dev_medias_front_rn.xcodeproj
          workspace-path: ios/dev_medias_front_rn.xcworkspace
          team-id: ${{ secrets.TEAM_ID }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          p12-base64: ${{ secrets.P12_KEY }}
          certificate-password: ${{ secrets.PW_CERT }}
          code-signing-identity: ${{ vars.CODE_SIGNING_IDENTITY }}
      
      - name: Create Metadata
        if: github.ref_name == 'prod'
        env: 
          GH_TOKEN: ${{ github.token }}
          repository: ${{ github.repository  }}
          run_id: ${{ github.run_id }}
        run: |
          mkdir -p fastlane/metadata/default
          mkdir -p fastlane/metadata/pt-BR
          mkdir -p fastlane/metadata/en-US
          release_notes=$(gh api "/repos/$repository/actions/runs/$run_id/approvals" --jq '.[0] | .comment' | xargs)
          echo "$release_notes"
          if [[ -n "$release_notes" ]]; then
            echo "$release_notes" > fastlane/metadata/default/release_notes.txt
            echo "$release_notes" > fastlane/metadata/pt-BR/release_notes.txt
            echo "$release_notes" > fastlane/metadata/en-US/release_notes.txt
          else
            echo "Ajustes de bugs e performance" > fastlane/metadata/default/release_notes.txt
            echo "Ajustes de bugs e performance" > fastlane/metadata/pt-BR/release_notes.txt
            echo "Fix bugs and improve performance" > fastlane/metadata/en-US/release_notes.txt
          fi
        working-directory: ios

      - name: Exec fastlane
        run: bundle exec fastlane ${{ github.ref_name }}
        env:
          APP_PATH: /Users/runner/work/dev_medias_front/dev_medias_front/output.ipa
          ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        working-directory: ios
