name: Build & Deploy to Play Store
on:
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  fastlane-deploy_play_store:
    name: Build & Deploy to Play Store
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Java Version
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Get dependencies
        run: npm install
      
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASS }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
        working-directory: android
      - name: Set Versions
        run: |
          current_version=$(perl -ne 'print "$1" if /"version":\s*"(.*?)"/' package.json)
          echo "versionName=$current_version" >> android/gradle.properties
          echo "versionCode=${{ github.run_number }}" >> android/gradle.properties

      - name: set env
        run: |
          echo "REACT_APP_GRADE_OPTIMIZER_URL=${{ vars.REACT_APP_GRADE_OPTIMIZER_URL }}" >> .env
          echo "REACT_APP_SUBJECTS_URL=${{ vars.REACT_APP_SUBJECTS_URL }}" >> .env

      - name: Build appbundle
        run: ./gradlew build --warning-mode all
        working-directory: android   

      - name: Exec fastlane
        run: bundle exec fastlane ${{ github.ref_name }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android